// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiEntity.Data;

#nullable disable

namespace WebApiEntity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230315101637_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiEntity.Models.Cliente", b =>
                {
                    b.Property<string>("cliente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDeb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cliente");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            cliente = "1",
                            DataCriacao = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "J.K. Rowling",
                            NomeFiscal = "J.K. Rowling",
                            TotalDeb = ""
                        },
                        new
                        {
                            cliente = "02555",
                            DataCriacao = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Aaaa J.K. Rowling",
                            NomeFiscal = "F.K. Nothing",
                            TotalDeb = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
